# Generated by Django 4.1.2 on 2022-11-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_delete_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
    ]
